[features]
seeds = false
skip-lint = false

[programs.devnet]
nodus_access = "EWDPQ97rnYJyjbB7rpFwCnnYse5KwA8fLRTsv8piuqCE"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node test/anchor-devnet.mjs"
